{
 "title": "MAB-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Absolute Kafka log",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(kafka_log_Log_LogEndOffset{topic !~ \"__.*\"}) by (partition, topic)) by (topic)"
    }
   ]
  },
  {
   "title": "DB Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_db_keys" }
   ]
  },
  {
   "title": "Kafka increase [5m] log",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(increase(kafka_log_Log_LogEndOffset{topic !~ \"__.*\"}[5m])) by (partition, topic)) by (topic)"
    }
   ]
  },
  {
   "title": "Number of Running Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs"
    }
   ]
  }
 ]
}