{
 "title": "TV dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "schema ingest 1 min response status counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_response_total{app =~ \"schema_ingest.*\", path !~ \".*metrics.*\", path !~ \".*health.*\"}[5m])) by (method, path, status)"
    }
   ]
  },
  {
   "title": "schema egress 5 min status counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_response_total{app =~ \"schema_egress.*\", path !~ \".*metrics.*\", path !~ \".*health.*\"}[5m])) by (status)"
    }
   ]
  },
  {
   "title": "Kafka increase [5m] log",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(increase(kafka_log_Log_LogEndOffset{topic !~ \"__.*\"}[5m])) by (partition, topic)) by (topic)"
    }
   ]
  },
  {
   "title": "Absolute kafka offsets log",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(kafka_log_Log_LogEndOffset{topic !~ \"__.*\"}) by (partition, topic)) by (topic)"
    }
   ]
  },
  {
   "title": "recognized users in enrich pageview [15m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flink_taskmanager_job_task_operator_Enrich_Pageviews_counterKRN[15m]) / increase(flink_taskmanager_job_task_operator_Enrich_Pageviews_counterEnrichTotal[15m])",
     "legendFormat": "recog_user_rate"
    },
    {
     "expr": "increase(flink_taskmanager_job_task_operator_Enrich_Pageviews_counterKRN[15m] offset 24h) / increase(flink_taskmanager_job_task_operator_Enrich_Pageviews_counterEnrichTotal[15m] offset 24h)",
     "legendFormat": "yesterday"
    }
   ]
  }
 ]
}